
import Link from "next/link";
import "./globals.css";


//similar to meta and title in html
export const metadata = {
  title: "Our First Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className=""
      >
        {children}
      </body>
    </html>
  );
}
